---
- name: Install Docker and Jenkins
  hosts: servers
  become: yes

  vars:
    java_package: "openjdk-11-jdk"
    jenkins_repo_url: "https://pkg.jenkins.io/debian-stable/jenkins.io.key"

  tasks:
    - name: Install prerequisites for Docker
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      when: ansible_facts['os_family'] == "Debian"

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Add Docker's official repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Docker on Ubuntu
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Docker on Amazon Linux
      yum:
        name: docker
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    ######### Jenkins installation #########

    - name: Download Jenkins GPG key
      apt_key:
        url: "{{ jenkins_repo_url }}"
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Add Jenkins repository
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Update apt cache
      apt:
        update_cache: yes
        state: latest
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Java
      apt:
        name: "{{ java_package }}"
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Jenkins
      apt:
        name: jenkins
        state: latest
      when: ansible_facts['os_family'] == "Debian"

    - name: Start Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "Debian"


#######  copy docker compose fikle to server ##########

    - name: copy compose to server
      copy:
        src: $pwd/docker-compose.yml
        dest: /home/ubnutu
